# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/lib/python3.7/site-packages/cmake-3.13.3-py3.7-macosx-10.14-x86_64.egg/cmake/data/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /usr/local/lib/python3.7/site-packages/cmake-3.13.3-py3.7-macosx-10.14-x86_64.egg/cmake/data/CMake.app/Contents/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jackyyuen/Codes/LinkedProcess

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jackyyuen/Codes/LinkedProcess

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/lib/python3.7/site-packages/cmake-3.13.3-py3.7-macosx-10.14-x86_64.egg/cmake/data/CMake.app/Contents/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/lib/python3.7/site-packages/cmake-3.13.3-py3.7-macosx-10.14-x86_64.egg/cmake/data/CMake.app/Contents/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jackyyuen/Codes/LinkedProcess/CMakeFiles /Users/jackyyuen/Codes/LinkedProcess/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jackyyuen/Codes/LinkedProcess/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named linked

# Build rule for target.
linked: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 linked
.PHONY : linked

# fast build rule for target.
linked/fast:
	$(MAKE) -f CMakeFiles/linked.dir/build.make CMakeFiles/linked.dir/build
.PHONY : linked/fast

src/Block.o: src/Block.c.o

.PHONY : src/Block.o

# target to build an object file
src/Block.c.o:
	$(MAKE) -f CMakeFiles/linked.dir/build.make CMakeFiles/linked.dir/src/Block.c.o
.PHONY : src/Block.c.o

src/Block.i: src/Block.c.i

.PHONY : src/Block.i

# target to preprocess a source file
src/Block.c.i:
	$(MAKE) -f CMakeFiles/linked.dir/build.make CMakeFiles/linked.dir/src/Block.c.i
.PHONY : src/Block.c.i

src/Block.s: src/Block.c.s

.PHONY : src/Block.s

# target to generate assembly for a file
src/Block.c.s:
	$(MAKE) -f CMakeFiles/linked.dir/build.make CMakeFiles/linked.dir/src/Block.c.s
.PHONY : src/Block.c.s

src/Distribute.o: src/Distribute.c.o

.PHONY : src/Distribute.o

# target to build an object file
src/Distribute.c.o:
	$(MAKE) -f CMakeFiles/linked.dir/build.make CMakeFiles/linked.dir/src/Distribute.c.o
.PHONY : src/Distribute.c.o

src/Distribute.i: src/Distribute.c.i

.PHONY : src/Distribute.i

# target to preprocess a source file
src/Distribute.c.i:
	$(MAKE) -f CMakeFiles/linked.dir/build.make CMakeFiles/linked.dir/src/Distribute.c.i
.PHONY : src/Distribute.c.i

src/Distribute.s: src/Distribute.c.s

.PHONY : src/Distribute.s

# target to generate assembly for a file
src/Distribute.c.s:
	$(MAKE) -f CMakeFiles/linked.dir/build.make CMakeFiles/linked.dir/src/Distribute.c.s
.PHONY : src/Distribute.c.s

src/Pipeline.o: src/Pipeline.c.o

.PHONY : src/Pipeline.o

# target to build an object file
src/Pipeline.c.o:
	$(MAKE) -f CMakeFiles/linked.dir/build.make CMakeFiles/linked.dir/src/Pipeline.c.o
.PHONY : src/Pipeline.c.o

src/Pipeline.i: src/Pipeline.c.i

.PHONY : src/Pipeline.i

# target to preprocess a source file
src/Pipeline.c.i:
	$(MAKE) -f CMakeFiles/linked.dir/build.make CMakeFiles/linked.dir/src/Pipeline.c.i
.PHONY : src/Pipeline.c.i

src/Pipeline.s: src/Pipeline.c.s

.PHONY : src/Pipeline.s

# target to generate assembly for a file
src/Pipeline.c.s:
	$(MAKE) -f CMakeFiles/linked.dir/build.make CMakeFiles/linked.dir/src/Pipeline.c.s
.PHONY : src/Pipeline.c.s

src/Street.o: src/Street.c.o

.PHONY : src/Street.o

# target to build an object file
src/Street.c.o:
	$(MAKE) -f CMakeFiles/linked.dir/build.make CMakeFiles/linked.dir/src/Street.c.o
.PHONY : src/Street.c.o

src/Street.i: src/Street.c.i

.PHONY : src/Street.i

# target to preprocess a source file
src/Street.c.i:
	$(MAKE) -f CMakeFiles/linked.dir/build.make CMakeFiles/linked.dir/src/Street.c.i
.PHONY : src/Street.c.i

src/Street.s: src/Street.c.s

.PHONY : src/Street.s

# target to generate assembly for a file
src/Street.c.s:
	$(MAKE) -f CMakeFiles/linked.dir/build.make CMakeFiles/linked.dir/src/Street.c.s
.PHONY : src/Street.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... linked"
	@echo "... src/Block.o"
	@echo "... src/Block.i"
	@echo "... src/Block.s"
	@echo "... src/Distribute.o"
	@echo "... src/Distribute.i"
	@echo "... src/Distribute.s"
	@echo "... src/Pipeline.o"
	@echo "... src/Pipeline.i"
	@echo "... src/Pipeline.s"
	@echo "... src/Street.o"
	@echo "... src/Street.i"
	@echo "... src/Street.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

